### ISSUE TITLE
Installed app doesn't work (blank window)

### ISSUE THREAD

**Issue by Catsvilles** [dawg/dawg#155] opened 2020-03-01 15:42 UTC
Hey guys, I tried to install latest release of Dawg on my machine, first I installed .deb package on my Ubuntu 18, when I started application only blank window is what I got. I thought this is a problem with my OS, so I tried to install Dawg on my another machine with Windows 7 on it. Same error - blank window. Before I was playing with previous version (Vusic), it launched but kinda didn't not work at all.
Also, I cannot start it from source code because I have node v11.15.0 installed and I get error that 10 is required. (Which probably is ok behaviour since it's my problem that I have different node version)
Any ideas? Looks like Dawg has the richest functionality from all Web Audio daws out there, so I just would like to play around it and try to compose something with it. 

P.S. why not also make web based version, for quick demos and stuff? I think this will be super attractive to potential users + Electron really eats lots of pc resources like CPU and ram, my CPU was jumping above 100% when I was starting Vusic.

**Comment by jsmith** [comment] 2020-03-03 17:27
Hey thanks for checking out this project :) I'm really sorry you had issues installing the application, do you mind if I ask what version you tried to install? The whole build process for Electron is a bit confusing and I recently switched to using GitHub actions from Travis CI to build the application for windows/mac/linux so I'm not very surprised there are issues. I can confirm that version 0.2.0 installed correctly on Mac OS but let me test out the installation process on a Windows laptop and get back to you! I'm on my spring break atm and have put in lots of work the past few days so I will be releasing a new version soon!

As for the node version issues, I pinned to 10.X.X (as you've noticed) due to node dependency issues but I successfully tested it on node 11 today and can confirm that at least the development server works. I've updated the version information in the package.json file and have merged this into master.

As for the web based version, I've come to realize that something like that would be very nice. I've thought about it before might do a bit more research. I use the node API heavily for project saving, configuration files, logging, and audio files but if I could find a way to abstract these things it would be super cool to have a web version for simple demos. I've actually created another issue for this (#158).

**Comment by Catsvilles** [comment] 2020-03-03 20:33
Hi, thanks for getting back to me! I was talking about 0.2.0 version, tried to run in on Ubuntu 18 and Windows 7. Will try to install it tomorrow again + plus maybe even build it from source. I can give some more feedback after that. I believe since node.js is used it should be quite easy to have web version running, working with local files and stuff.
Btw, have you known about wams (https://www.webaudiomodules.org/) ampedstudio is an online DAW and appears to be using them. I don't have experience with those but thought you might be interested since you are aiming towards fully featured DAW. Also, I believe with WebAssembly on rise nowadays it should be quite possible to build something powerful and fully featured, in any case :)

**Comment by jsmith** [comment] 2020-03-03 21:48
Ok let me know how it goes! You will definitely find bugs but I am making a big push to stabilize and improve the reliability of the core features :) 

Most of the application can easily run in the browser; however, I access native APIs and the file system using the `electron` and `fs` modules. These will have to be mocked somehow. I'm finding some good resources though which will be useful in this effort (they are linked in the issue I created).

Thanks for the link to amped studio, I actually hadn't heard of them so this will be a good reference 😄I'll also look into wams but yes I'm hoping to eventually push the limits the DAWs in the web using Web Assembly! One more thing, have you looked at @gridsound?

**Comment by jsmith** [comment] 2020-03-05 01:36
I just tested on Windows 10 and it did install correctly for me (ie. it wasn't showing a blank screen); however, there seems to be a startup issue as only part of the interface loaded. I'm going to work on these tomorrow!

**Comment by jsmith** [comment] 2020-03-05 14:24
Ok one more update, I just merged #166 (and released 0.2.3) to resolve the issues I found. I'm not sure if this will help in your situation as I still can't confirm it will work on Windows 7 or Ubuntu at the moment. I also updated the "Getting Started" guide with better instructions for Windows :)

**Comment by Catsvilles** [comment] 2020-03-06 19:13
Hi! Just installed it on my Ubuntu machine (I actually don't care about the Windows version, was just testing it before). Well, it launched, I was even able to import .wav file, but I guess I'm getting same issues as I was getting before with previous version (before  0.2.0). Cannot see the Piano roll, the timeline (I guess it can be called Transport, since it's based on Tone.js) is not starting, and yes I've added pattern, but it's just an empty one since Piano roll is not there. Well, I believe those also can be issues on my side (I really wanted all the time to inspect the page and see what's up in the console lol). It is unfortunate I couldn't fully test it but I like the GUI very much, good work on this one, for sure :)
Please, note that you shouldn't waste your time trying to fix those, as I was just passing by and wanted to test what's up here. I think you should better concentrate on continuing developing what you planned, eventually all those things can be fixed anyway. (Also there is a chance these issues are coming from Tone.js, so simply upgrading your Tone.js versions can be the key, also consider switching to their Typescript version, I guess?)
Yeah, I've heard about @gridsound, left them idea/issue of ability to use .wav
 samples in the Piano Roll, not so long ago.
Web version could be cool, but also since you are using Electron anyway, consider taking a look at https://github.com/ramirezd42/node-audio - graph-based audio api for Node.js based on LabSound and JUCE, and https://github.com/ramirezd42/schmix DAW written which uses those.

**Comment by jsmith** [comment] 2020-03-08 23:04
Thanks for the feedback! I'm assuming you installed a version < 0.2.2 as I enabled the "Inspect" command in production on that version. I was also super frustrated not being able to inspect while I was debugging the issues so I quickly released that update haha.

Anyway thanks again for the help and glad you like the GUI :) I'll hopefully be able to test on Linux sometime soon to make sure there aren't any other platform issues!

**Closed** 2020-03-09 08:54 UTC
